# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from waitdavid import WebDriverWaitDavid
import elementdavid
import projectdavid
import pyperclip

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()

    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def david(self):
    elementdavid.fieldotherchargeitem1 = "//li[contains(.,\'機票服務:機票服務\')]" #HOFIX TC0139
    elementdavid.fieldotherchargeitem2 = "//li[contains(.,\'機票升級:機票升級\')]"



    #
    # elementdavid.fieldotherchargeitem1 = "//li[contains(.,\'當地享樂:當地享樂\')]"   #staging TC0139
    # elementdavid.fieldotherchargeitem2 = "//li[contains(.,\'一日遊:一日遊\')]"

    # elementdavid.fieldotherchargeitem1 = "//li[contains(.,\'酒店服務:酒店服務\')]"   #hofix TC0179
    # elementdavid.fieldotherchargeitem2 = "//li[contains(.,\'一日遊:一日遊\')]"

    # elementdavid.fieldotherchargeitem1 = "//li[contains(.,\'個人服務:翻譯\')]"
    # elementdavid.fieldotherchargeitem2 = "//li[contains(.,\'交通:機場大巴\')]"
    # elementdavid.fieldotherchargeitem1 = "/html/body/div[2]/div/div/div/ul/li[1]"
    # elementdavid.fieldotherchargeitem2 = "/html/body/div[2]/div/div/div/ul/li[2]"
    # elementdavid.web = "http://test.traveloptimizer.travelconnect.co/#/login"
    # elementdavid.textaccount = "test@travelconnect.co"
    # elementdavid.textpassword = "123456789"
    # # elementdavid.textaccount = "david"
    # # elementdavid.textpassword = "Travel2021"
    # # elementdavid.textaccount = "wwpkg@travelconnect.co"
    # # elementdavid.textpassword = "wwpkg123"
    # elementdavid.textcompanycode = "TC0179"

    # 發票收款部分
    elementdavid.textbooking_invoice_item_receipt_bankchage = "1"
    elementdavid.textbooking_invoice_item_receipt_creditchage = "2"
    # 發票退款部分
    elementdavid.textbooking_invoice_item_refund_fare = "1"
    elementdavid.textbooking_invoice_item_refund_bankchage = "1"
    elementdavid.textbooking_invoice_item_refund_creditchage = "2"

    elementdavid.textothercharge_invoice1 = "201"
    elementdavid.textothercharge_xo1 = "100"


    projectdavid.login(self)
    projectdavid.riseinvoice(self)
    # projectdavid.riseremark(self)
    # projectdavid.apiticket(self)
    # projectdavid.handticket1(self)
    # projectdavid.handticket2(self)
    # projectdavid.handhotel1(self)
    # projectdavid.handhotel2(self)
    projectdavid.othercharge1(self)
    # projectdavid.othercharge2(self)
    # projectdavid.daytour1(self)
    # projectdavid.daytour2(self)
    projectdavid.nextpage(self)
    # projectdavid.nextpageadditem(self)
    # projectdavid.group13579(self)
    # projectdavid.passengerall(self)
    projectdavid.finalcheck(self)
    # projectdavid.inputwaiting(self)


    projectdavid.printout_booking(self)
    projectdavid.riseinvoice_xo(self)
    projectdavid.finalcheck(self)
    #
    # projectdavid.printout_booking(self)
    # projectdavid.riseinvoice_receipt(self)
    # projectdavid.printout_booking(self)
    # projectdavid.riseinvoice_refund(self)
    # projectdavid.printout_booking(self)
    # projectdavid.risexo_receipt(self)
    # projectdavid.printout_booking(self)
    # projectdavid.risexo_refund(self)


    # projectdavid.finalcheck(self)



  
if __name__ == '__main__':
  test = Test()
  test.setup_method(0)
  test.david()
  # print("输入内容进行关闭 ", input("请输入："))
  # test.teardown_method()