# Generated by Selenium IDE
import pytest
import time
import json
# from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from waitdavid import WebDriverWaitDavid
import elementdavid
import projectdavid
from webdriver_helper import get_webdriver
import pyperclip


class Test():
    def setup_method(self, method):
        self.driver = get_webdriver("chrome")

        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def david(self):
        elementdavid.web = "https://system.tripo.ai/#/login"
        # elementdavid.web = "http://tripo.staging.travelconnect.co/#/login"
        elementdavid.textaccount = "test@travelconnect.co"
        elementdavid.textpassword = "123456789"
        # elementdavid.textaccount = "david"
        # elementdavid.textpassword = "Travel2021"
        elementdavid.textcompanycode = "TC0204"
        elementdavid.textothercharge_remark1 = "備註"
        elementdavid.textothercharge_invoice1 = "201"
        elementdavid.textothercharge_xo1 = "100"
        elementdavid.fieldotherchargeitem1 = "//li[contains(.,\'機票服務:機票服務\')]"  # HOFIX TC0139
        elementdavid.fieldotherchargeitem2 = "//li[contains(.,\'機票升級:機票升級\')]"
        #創建報價單
        projectdavid.login(self)
        projectdavid.risequotation(self)
        projectdavid.othercharge1(self)
        projectdavid.nextpage(self)
        projectdavid.passenger1(self)
        projectdavid.inputwaiting(self)
        # projectdavid.finalcheck(self)
        #報價單轉發票和xo
        # projectdavid.login(self)
        # projectdavid.risebooking(self)
        projectdavid.printout_booking(self)

        projectdavid.risequotation_invoice(self)
        projectdavid.printout_booking(self)
        projectdavid.risequotation_xo(self)
        projectdavid.printout_booking(self)
        #發票退款和付款
        # projectdavid.login(self)
        # projectdavid.risebooking(self)
        # projectdavid.printout_booking(self)
        projectdavid.riseinvoice_receipt(self)
        projectdavid.printout_booking(self)
        projectdavid.riseinvoice_refund(self)
        projectdavid.printout_booking(self)

        #xo付款和退款
        # projectdavid.printout_booking(self)
        projectdavid.risexo_receipt(self)
        projectdavid.printout_booking(self)
        projectdavid.risexo_refund(self)
        projectdavid.printout_booking(self)



if __name__ == '__main__':
    test = Test()
    test.setup_method(0)
    test.david()
    # print("输入内容进行关闭 ", input("请输入："))
    # test.teardown_method()