# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from waitdavid import WebDriverWaitDavid
import elementdavid
import projectdavid
import pyperclip


class Test():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()

        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def david(self):
        # elementdavid.web = "https://system.tripo.ai/#/login"
        # elementdavid.web = "http://tripo.staging.travelconnect.co/#/login"
        elementdavid.web = "http://test.traveloptimizer.travelconnect.co/#/login"
        elementdavid.textaccount = "wwpkg@travelconnect.co"
        elementdavid.textpassword = "wwpkg123"
        elementdavid.textcompanycode = "TC0008"
        projectdavid.login(self)
        projectdavid.risequotation(self)
        # projectdavid.riseremark(self)
        projectdavid.apiticket(self)
        projectdavid.handticket1(self)
        projectdavid.handticket2(self)
        projectdavid.handhotel1(self)
        projectdavid.handhotel2(self)
        projectdavid.othercharge1(self)
        projectdavid.othercharge2(self)
        projectdavid.daytour1(self)
        projectdavid.daytour2(self)
        projectdavid.nextpage(self)
        # projectdavid.nextpageadditem(self)
        # projectdavid.othercharge1(self)
        # projectdavid.nextpage(self)
        projectdavid.group13579(self)
        projectdavid.passengerall(self)
        projectdavid.inputwaiting(self)
        projectdavid.finalcheck(self)
        projectdavid.finalcheck(self)


if __name__ == '__main__':
    test = Test()
    test.setup_method(0)
    test.david()
    # print("输入内容进行关闭 ", input("请输入："))
    # test.teardown_method()