# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from waitdavid import WebDriverWaitDavid
import elementdavid
import projectdavid
import pyperclip

from webdriver_helper import get_webdriver


# 例子1 自动安装浏览器驱动、安装selenium等库、启动浏览器、截图


class Test():
    def setup_method(self, method):
        self.driver = get_webdriver("chrome")

        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def david(self):
        # elementdavid.fieldotherchargeitem1 = "//li[contains(.,\'機票服務:機票服務\')]" #HOFIX TC0139
        # elementdavid.fieldotherchargeitem2 = "//li[contains(.,\'機票升級:機票升級\')]"
        #
        elementdavid.fieldotherchargeitem1 = "//li[contains(.,\'當地享樂:當地享樂\')]"  # staging TC0139
        elementdavid.fieldotherchargeitem2 = "//li[contains(.,\'一日遊:一日遊\')]"

        # elementdavid.fieldotherchargeitem1 = "//li[contains(.,\'酒店服務:酒店服務\')]"   #hofix TC0179
        # elementdavid.fieldotherchargeitem2 = "//li[contains(.,\'一日遊:一日遊\')]"

        # elementdavid.fieldotherchargeitem1 = "//li[contains(.,\'個人服務:翻譯\')]"
        # elementdavid.fieldotherchargeitem2 = "//li[contains(.,\'交通:機場大巴\')]"
        # elementdavid.fieldotherchargeitem1 = "/html/body/div[2]/div/div/div/ul/li[1]"
        # elementdavid.fieldotherchargeitem2 = "/html/body/div[2]/div/div/div/ul/li[2]"
        # elementdavid.web = "http://test.traveloptimizer.travelconnect.co/#/login"
        # elementdavid.textaccount = "test@travelconnect.co"
        # elementdavid.textpassword = "123456789"
        # # elementdavid.textaccount = "david"
        # # elementdavid.textpassword = "Travel2021"
        # # elementdavid.textaccount = "wwpkg@travelconnect.co"
        # # elementdavid.textpassword = "wwpkg123"
        # elementdavid.textcompanycode = "TC0179"

        projectdavid.login(self)
        projectdavid.riseinvoice(self)
        # projectdavid.riseremark(self)
        # projectdavid.apiticket(self)
        # projectdavid.handticket1(self)
        # projectdavid.handticket2(self)
        projectdavid.handapiticket1(self)
        # projectdavid.handhotel1(self)
        # projectdavid.handhotel2(self)

        projectdavid.othercharge1(self)
        # projectdavid.othercharge2(self)
        # projectdavid.daytour1(self)
        # projectdavid.daytour2(self)
        projectdavid.nextpage(self)
        # projectdavid.nextpageadditem(self)
        # projectdavid.group13579(self)
        projectdavid.passengerall(self)

        projectdavid.inputwaiting(self)
        #
        # projectdavid.printout_booking(self)
        # projectdavid.riseinvoice_xo(self)
        # projectdavid.printout_booking(self)
        # projectdavid.riseinvoice_receipt(self)
        # projectdavid.printout_booking(self)
        # projectdavid.riseinvoice_refund(self)
        # projectdavid.printout_booking(self)
        # projectdavid.riseinvoice_refundapplication(self)
        # projectdavid.printout_booking(self)
        # projectdavid.inputwaiting(self)
        # projectdavid.finalcheck(self)


if __name__ == '__main__':
    test = Test()
    test.setup_method(0)
    test.david()
    # print("输入内容进行关闭 ", input("请输入："))
    # test.teardown_method()