# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from waitdavid import WebDriverWaitDavid
import elementdavid
import projectdavid
import pyperclip


class Test():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()

        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def david(self):
        elementdavid.fieldotherchargeitem1 = "//li[contains(.,\'機票服務:機票服務\')]" #HOFIX TC0139
        elementdavid.fieldotherchargeitem2 = "//li[contains(.,\'機票升級:機票升級\')]"
        #
        # elementdavid.fieldotherchargeitem1 = "//li[contains(.,\'當地享樂:當地享樂\')]"  # staging TC0139
        # elementdavid.fieldotherchargeitem2 = "//li[contains(.,\'一日遊:一日遊\')]"
        # # elementdavid.fieldotherchargeitem1 = "/html/body/div[2]/div/div/div/ul/li[1]"

        # # elementdavid.fieldotherchargeitem2 = "/html/body/div[2]/div/div/div/ul/li[2]"
        # elementdavid.textaccount = "test@travelconnect.co"
        # elementdavid.textpassword = "123456789"
        # # elementdavid.textaccount = "david"
        # # elementdavid.textpassword = "Travel2021"
        # elementdavid.textcompanycode = "TC0008"


        projectdavid.login(self)
        projectdavid.risexo(self)
        # projectdavid.riseremark(self)
        projectdavid.apiticket(self)
        projectdavid.handticket1(self)
        projectdavid.handticket2(self)
        projectdavid.handhotel1(self)
        projectdavid.handhotel2(self)
        projectdavid.othercharge1(self)
        projectdavid.othercharge2(self)
        projectdavid.daytour1(self)
        projectdavid.daytour2(self)
        projectdavid.nextpage(self)
        # projectdavid.nextpageadditem(self)
        # projectdavid.othercharge1(self)
        # projectdavid.nextpage(self)
        # projectdavid.group13579(self)
        projectdavid.passengerall(self)

        projectdavid.inputwaiting(self)
        projectdavid.nextpageadditem(self)
        projectdavid.apiticket(self)
        projectdavid.handticket1(self)
        projectdavid.handticket2(self)
        projectdavid.handhotel1(self)
        projectdavid.handhotel2(self)
        projectdavid.othercharge1(self)
        projectdavid.othercharge2(self)
        projectdavid.daytour1(self)
        projectdavid.daytour2(self)

        projectdavid.inputwaiting(self)

        projectdavid.printout_booking(self)
        projectdavid.risexo_invoice(self)
        projectdavid.printout_booking(self)
        projectdavid.risexo_quotation(self)
        projectdavid.printout_booking(self)
        projectdavid.risexo_refundapplication(self)
        projectdavid.printout_booking(self)
        projectdavid.risexo_receipt(self)
        projectdavid.printout_booking(self)
        projectdavid.risexo_refund(self)
        projectdavid.printout_booking(self)





if __name__ == '__main__':
    test = Test()
    test.setup_method(0)
    test.david()
    # print("输入内容进行关闭 ", input("请输入："))
    # test.teardown_method()